### ISSUE TITLE
Please guide in executing this project

### ISSUE THREAD

**Issue by IamVaibhavsar** [vipul79321/Handwritten-Equation-Solver#1]
Hii vipul,
I have downloaded this repository and of handwritten Equation solver and extracted it. Do you please guide me in executing this project in windows 10 environment. as I am developing my college project using CNN.

Thank You.

**Comment by vipul79321** [comment]
@IamVaibhavsar  I have updated the readme file, and I hope it is quite clear now.

**Comment by IamVaibhavsar** [comment]
I tried running the first file  (data_extraction.ipynb) in jupyter notebook
but its showing errors (screenshot is attached)
can you make video from downloading this repository to successfully running
the project.
my whatsapp no. is 9689081596
Thank you in advance.
